title: Ronin's topics
description: A simple site exploring various technology topics
baseurl: "/ronin"
url: "https://b1rr0.github.io"

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme